### ISSUE TITLE
Error with serverless-esbuild

### ISSUE THREAD

**Issue by fabioginzel** [lumigo-io/serverless-lumigo-plugin#121]
See this thread https://github.com/floydspace/serverless-esbuild/issues/340

**Comment by nirLumigo** [comment]
Thank you for raising the issue. We will check it and update.

**Comment by doriaviram** [comment]
Hey, @fabioginzel, We working on a fix. We will keep you posted
https://github.com/lumigo-io/serverless-lumigo-plugin/pull/122.
