### ISSUE TITLE
Import error when used in combination with zipped python-requirements

### ISSUE THREAD

**Issue by javimudi** [lumigo-io/serverless-lumigo-plugin#29]
Hi,

I just installed the tracer and I noticed that, when adding the zipping option to the 'serverless-python-requirements' plugin my lambdas are raising an ImportError Exception:
```
{
  "errorMessage": "Unable to import module '_lumigo/DetectDominantLanguageCode': No module named 'lumigo_tracer'",
  "errorType": "Runtime.ImportModuleError"
}
```

Best,
Javier

**Comment by efimk-lu** [comment]
Hi @javimudi ,
Thank you very much for taking the time to open an issue.

Can you please attach the following:
* serverless.yml plugin section
* The full configuration of serverless-python-requirements under custom.

Tx!

**Comment by javimudi** [comment]
Hi @efimk-lu ,

Sure!

My serverless plugin section:
```
plugins:
  - serverless-python-requirements
  - serverless-plugin-git-variables
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-s3-sync
  - serverless-lumigo
```

And the config:

```
pythonRequirements:
  dockerizePip: true
  zip: true
```

Thanks!

I'm open to providing some more context if required.

**Comment by efimk-lu** [comment]
@javimudi can you please share your `requirements.txt file`

**Comment by javimudi** [comment]
Hello,

```
moviepy==1.0.1
environs==5.2.1
boto3==1.9.146
requests==2.22.0
lumigo_tracer==1.1.74
```

These are the packages I'm using for my stack. I was using compression and exactly the same packages, besides `lumigo_tracer`, of course, before integrating.

For instance, I'm using a similar setup with a different stack without compressed requirements and it works perfectly.

**Comment by javimudi** [comment]
Hi again,

I went a bit deeper into the code and the zip package created by the Serverless framework to deploy the stack is actually wrapping every function, but since the requirements are zipped, `lumigo_tracer` cannot be imported until `unzip_requirements` is called, as explained [here](https://www.npmjs.com/package/serverless-python-requirements#dealing-with-lambdas-size-limitations):
```python
try:
  import unzip_requirements
except ImportError:
  pass
```
I guess if I manually include the import somewhere around [here](https://github.com/lumigo-io/serverless-lumigo-plugin/blob/master/src/index.js#L329) the wrapped function would work again.

Best

**Comment by efimk-lu** [comment]
@javimudi you are absolutely right, we are working on adding it as we speak. Tx!

**Comment by efimk-lu** [comment]
@javimudi we've released a PR. there are some issues missing before actually merging it master. Can you check it and see if it helps you? https://github.com/lumigo-io/serverless-lumigo-plugin/pull/30

**Comment by javimudi** [comment]
Yep! Looks great to me. Thank you!

I already tweaked my local code to include the `unzip_requirements` bit and it worked, so, as long as I don't reinstall from `npm` it'll keep on working.

I will update when you release, no problem.

Thanks again!
