### ISSUE TITLE
 No matching handler found for 'lumigo-auto-instrument' 

### ISSUE THREAD

**Issue by playdaygameschris** [lumigo-io/serverless-lumigo-plugin#53]
I found that if i install with serverless-bundle plugin, which included webpack will throw an error ` No matching handler found for 'lumigo-auto-instrument' ` when sls deploy. Are there any work around? thanks

**Comment by efimk-lu** [comment]
Hey @playdaygameschris , 
In case you want to manage the Lumigo tracer dependency yourself - e.g. you want to use Lerna or Webpack, and can't have this plugin install the Lumigo tracer on your behalf on every deployment - then you can also disable the NPM install process altogether.

See https://github.com/lumigo-io/serverless-lumigo-plugin#nodejs-functions

**Comment by akleiber** [comment]
Hi. I also get this message.
We use https://github.com/serverless-heaven/serverless-webpack/ for automatic packaging. It seems that the plugin can not find the auto generated handler from lumigo.

Any advice on how to setup Lumigo in this case? 
I would love to use lambda layers.

**Comment by akleiber** [comment]
Okay - do we even need to do this if we setup auto tracing? I guess no, right?

**Comment by efimk-lu** [comment]
Hey! In case you use auto tracing, no need to use the plugin.
