### ISSUE TITLE
No matching handler found for 'lumigo-auto-instrument'

### ISSUE THREAD

**Issue by lionheart2013** [lumigo-io/serverless-lumigo-plugin#55]

**Comment by efimk-lu** [comment]
Hi @lionheart2013 , can you share your:
* Serverless plugin configuration
* Lumigo's plugon configuration

**Comment by lionheart2013** [comment]
> Hi @lionheart2013 , can you share your:
> 
> * Serverless plugin configuration
> * Lumigo's plugon configuration

nothing fancy, just installed this plugin with the configuration below:

plugins:
  - serverless-lumigo
  - serverless-bundle
custom:
  lumigo:
    token: <YOUR TOKEN GOES HERE>
    useLayers: true

**Comment by lionheart2013** [comment]
FYI, error gone if I removed serverless-bundle, unfornately produced another error "Cannot find module './lumigo-auto-instrument.js"

**Comment by efimk-lu** [comment]
@lionheart2013 are you auto instrumenting this function as well?

**Comment by efimk-lu** [comment]
I mean did you do this - https://docs.lumigo.io/docs/auto-instrumentation and instrumented via the plugin?

**Comment by efimk-lu** [comment]
@lionheart2013 please remove useLayers: true tell me if it works then

**Comment by lionheart2013** [comment]
> @lionheart2013 please remove useLayers: true tell me if it works then

removing useLayers: true, cause an eslint error and these error cannot be ignored for some reason. Tried to ignore _lumigo directory but nothings happen. Also turning off useLayers is not an option for this one this feature is part of our requirements.

<img width="1148" alt="Screen Shot 2020-11-30 at 10 12 24 PM" src="https://user-images.githubusercontent.com/5111948/100620829-d4c94c00-3359-11eb-85d6-8fb040aa24df.png">

**Comment by efimk-lu** [comment]
@lionheart2013 we can have a quick zoom meeting to sort this thing out, when are you available? Is the email listed under your GitHub account is a valid email?

**Comment by lionheart2013** [comment]
> @lionheart2013 we can have a quick zoom meeting to sort this thing out, when are you available? Is the email listed under your GitHub account is a valid email?

Thats great, yes the email address under my Github account is valid. I am available this week from 1pm onwards just let me know. Thank you.

**Comment by efimk-lu** [comment]
@lionheart2013 sent an email
