### ISSUE TITLE
Why does this plugin require a token while the auto-tracer doesn't?

### ISSUE THREAD

**Issue by bartvollebregt** [lumigo-io/serverless-lumigo-plugin#59]
Hi!

First of all I really like what you're doing! I might be overlooking something but I would like to understand how it works.

I've created the `LumigoIntegrationV6` Cloudformation stack in AWS.  When using the auto tracer functionality it will automatically connect the `lumigo-python-tracer` Layer to my Lambda function (I'm using Python).
Using this method, no extra token is required. I assume this uses CF stack (maybe the `ExternalId` parameter?) to communicate with Lumigo.

When using this plugin, I have to add a token which feels a bit unnecessary. Maybe the  `LumigoIntegration` stack can create a pre-filled, encrypted SSM parameter for the token which then can be used automatically by this plugin?

**Comment by nirLumigo** [comment]
Hi,
Thank you for the suggestion :)

The auto-tracing functionality doesn't use a token from the CF stack, the token is embedded when the lambda is auto-traced. Also, the CF stack doesn't have the token as an output.

There a are a few more issues:
- We don't control the permissions of the user's lambda. If we'll publish the token, the lambda might not have permissions to access it.
- A user might have multiple Lumigo projects in the same account. In this case there will also be multiple CF stacks in the same account and each stack will have a different token. We need to be able to match each lambda to the relevant CF stack.

**Comment by bartvollebregt** [comment]
I see. Thanks for clearing this up!
