### ISSUE TITLE
support nodejs14.x runtime

### ISSUE THREAD

**Issue by pokryfka** [lumigo-io/serverless-lumigo-plugin#61]
This goes beyond the plugin itself, but it would be great if Lumigo officially supported nodejs14.x runtime

**Comment by nirLumigo** [comment]
Lumigo supports nodejs14.x: https://github.com/lumigo-io/lumigo-node

**Comment by pokryfka** [comment]
Thank you for the clarification.
There are no layers for nodejs14.x runtime, I understand I should be using the layers for nodejs12.x runtime?
(they do work well, based on my very limited experience)

https://github.com/lumigo-io/lumigo-node/tree/master/layers

**Comment by nirLumigo** [comment]
You don't need to manually handle the layers, just click on the "Traced" button in the UI:
![image](https://user-images.githubusercontent.com/49228804/113986842-612ed280-9856-11eb-9183-642c1aa6f199.png)

**Comment by efimk-lu** [comment]
Hey @pokryfka the list is updated.
