### ISSUE TITLE
Support PNPM

### ISSUE THREAD

**Issue by kevinoneill** [lumigo-io/serverless-lumigo-plugin#72]
PNPM is an alternate package manager to yarn and npm, the most notable of which are generally faster performance and package isolation.

**Comment by benheymink** [comment]
Just hit this too :-(

**Comment by GuyMoses** [comment]
Hey guys! @kevinoneill @benheymink 
thanks for the request

merged: https://github.com/lumigo-io/serverless-lumigo-plugin/pull/119
